---
# tasks file for manage-apache-vhost
- name: "Ensure directory structure and custom scripts are present"
  include_tasks: prerequisites.yml

- name: "Manage vhosts."
    include_task: manageVhosts.yml
    loop: "{{ vhost_vars }}"