---
collections:
  - name: community.general
  - name: community.docker
  - name: community.kubernetes
  - name: community.mongodb
  - name: community.network
  - name: community.mysql
  - name: community.postgresql
  - name: ansible.posix
