  - name: "Install dnf"
    yum:
      name: "dnf"
      state: "latest"
    tags: 
      - basic
  
  - name: "Update OS"
    dnf:
      name: "*"
      state: "latest"
    tags: 
      - basic
  
  - name: "Install EPEL repo"
    include_role: ansible-role-repo-epel
      apply:
        tags:
          - basic
    tags: 
      - basic
    ignore_errors: no

  - name: "Install Remi repo"
    include_role: ansible-role-repo-remi
      apply:
        tags:
          - basic
    tags: 
      - basic
    ignore_errors: no

# only needed for EPEL v8
  - name: "Activate PowerTools repo"  
    command: "dnf config-manager --set-enabled PowerTools"
    ignore_errors: no
    tags: 
      - basic
