  - name: "Install dnf"
    yum:
      name: "dnf"
      state: "latest"
  
  - name: "Update OS"
    dnf:
      name: "*"
      state: "latest"
  
  - name: "Install EPEL repo"
    dnf: 
# might be a variable
      name: " https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
      state: "latest"
    ignore_errors: yes

# only needed for EPEL v8
  - name: "Activate PowerTools repo"  
    command: "dnf config-manager --set-enabled PowerTools"
    ignore_errors: yes
