- firewalld:
    port: "{{ item.port }}"
    permanent: "{{ item.permanent }}"
    state: "{{ item.state }}"
  become: true
  become_user: "root"
  notify: "Restart firewalld"
  tags: 
    - basic
    - secured