---
- name: Basic requirements
  include_tasks: basic_prerequirements.yml
  tags:
    - basic

- name: Create initial users
  include_tasks: manageUsers.yml 
  with_items: '{{ user_vars }}'
  ignore_errors: yes
  tags: 
    - basic
- meta: clear_host_errors  

- name: Manage Users
  include_tasks: manageUsers.yml
  with_items: '{{ user_vars }}'
  ignore_errors: yes
  tags: 
    - secured
- meta: clear_host_errors  

- name: Set Custom ssh Settings
  include_tasks: customSshSettings.yml
  tags: 
    - basic

- name: Secure VPS 2
  include_tasks: secureVPS2.yml
  tags: 
    - secured