---
- name: Basic requirements
  import_tasks: basic_prerequirements.yml
  tags:
    - basic

- name: Create initial users
  include_tasks: manageUsers.yml
  vars:
    - managedUsers:'{{ user_vars }}'
  ignore_errors: yes
  tags: 
    - basic
- meta: clear_host_errors  

- name: Manage Users
  include_tasks: manageUsers.yml
  vars:
    - managedUsers:'{{ user_vars }}'
  ignore_errors: yes
  tags: 
    - secured
- meta: clear_host_errors  

- name: Secure VPS 1
  include_tasks: secureVPS1.yml
  tags: 
    - basic

- name: Secure VPS 2
  include_tasks: secureVPS2.yml
  tags: 
    - secured