---
- name: "Add non-root user(s)"
  user:
    name: "{{ user_vars.username }}"
    groups: "{{ user_vars.groups }}"
    append: "{{ user_vars.append_groups }}"
    state: "{{ user_vars.create }}"
    remove: "{{ user_vars.delete }}"

- name: "Set authorized keys taken from url"
  authorized_key:
    user: "{{ user_vars.username }}"
    state: "{{ user_vars.create }}"
    key: "https://github.com/ea-p/SecureVPS/tree/master/files/{{ user_vars.keyname }}.pub"