---
- name: "Add non-root user(s)"
  user:
    name: "{{ username }}"
    groups: "{{ groups }}"
    append: "{{ append_groups }}"
    state: "{{ create }}"
    remove: "{{ delete }}"
  tags: basic, secured

- name: "Set authorized keys taken from url"
  authorized_key:
    user: "{{ username }}"
    state: "{{ create }}"
    key: "https://raw.githubusercontent.com/ea-p/SecureVPS/master/SecureVPS/files/{{ keyname }}.pub"
  tags: basic, secured