---
- name: "Add non-root user(s)"
  user:
    name: "{{ managedUsers.username }}"
    groups: "{{ managedUsers.groups }}"
    append: "{{ managedUsers.append_groups }}"
    state: "{{ managedUsers.create }}"
    remove: "{{ managedUsers.delete }}"

- name: "Set authorized keys taken from url"
  authorized_key:
    user: "{{ managedUsers.username }}"
    state: "{{ managedUsers.create }}"
    key: "https://github.com/ea-p/SecureVPS/tree/master/files/{{ managedUsers.keyname }}.pub"