---
- name: "Add non-root user(s)"
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    append: "{{ item.append_groups }}"
    state: "{{ item.create }}"
    remove: "{{ item.delete }}"
  tags: basic, secured

- name: "Set authorized keys"
  authorized_key:
    user: "{{ item.username }}"
    state: "{{ item.create }}"
    key: "{{ item.keyname }}"
  tags: basic, secured