---
- name: "Change ssh port"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^(#|\\s*)Port"
    line: "Port {{ ssh_port }}"
  notify: "Restart sshd"
  tags: 
    - basic

- name: "Disable remote root login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^(#|\\s*)PermitRootLogin"
    line: "PermitRootLogin no"
  notify: "Restart sshd"
  tags: 
    - basic

- name: "Disable password login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "(#|\\s*)PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: "Restart sshd"
  tags: 
    - basic
  
