---
- name: "Change ssh port"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "#^Port|^Port"
    line: "Port {{ ssh_port }}"
  notify: "Restart sshd"
  tag: 
    - basic

- name: "Disable remote root login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PermitRootLogin|^?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: "Restart sshd"
  tag: 
    - basic

- name: "Disable password login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PasswordAuthentication|^?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: "Restart sshd"
  tag: 
    - basic
  
