---
# tasks file for docker
- name: Install docker
  dnf:
    name: "{{ item }}"
    state: latest
    enablerepo: https://download.docker.com/linux/centos/docker-ce.repo
  with_items:
    - docker-ce
    - docek-ce-cli
    - containerd.io