---
# tasks file for wordpress
- name: Delete /tmp/wordpress if it exists
  file:
    path: /tmp/wordpress
    state: absent
  ignore_errors: true
  tags: wordpress

- name: Download the wp archive to tmp and unzip
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp
    remote_src: yes
    force: yes
  tags: wordpress

- name: Create wordpress data folder
  file:
    path: '{{ wordpress_data_path }}'
    state: directory
    mode: '0777'
  become: yes
  tags: wordpress

- name: Copy wordpress files to data folder
  copy:
    src: /tmp/wordpress/
    dest: '{{ wordpress_data_path }}'
    remote_src: yes
  tags: wordpress

- name: Create wp-config.php
  template:
    src: wp-config.php.j2
    dest: '{{ wordpress_data_path }}/wp-config.php'
  tags: wordpress
  become: yes

- name: Create DB
  mysql_db:
    name: "{{ wordpress_db_name }}"
    collation: "{{ vars[wordpress_db_charset + '_general_ci'] | default('utf8mb4_general_ci') }}"
    encoding: "{{ wordpress_db_charset | default('utf8') }}"
  tags: wordpress

- name: Create DB User
  mysql_user:
    name: "{{ wordpress_db_user }}"
    host: "{{ wordpress_db_host | default('localhost') }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{wordpress_db_name }}.*:ALL,GRANT"
    append_privs: "{{ append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  no_log: true
  tags: wordpress

- name: Create vhost for wp
  include_role: 
    name: manage-apache-vhost
    apply:
        tags: wordpress
  vars:
    - vhost_vars: "{{ wordpress_vhost }}"  
  tags: wordpress

  