---
# tasks file for docker
- name: Install docker repo
  command: 'dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
  become: yes
  become_user: root
  tags: docker

- name: Uninstall any podman-docker
  dnf:
    name: docker
    state: absent
  tags: docker

- name: Install docker
  dnf:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
  tags: docker

- name: Enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes 
  tags: docker

- name: Install portainer agent
  shell: 'docker run -d -p 9513:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent'
  tags: docker