---
# tasks file for customizeVPS
- name: "Install all tools used"
  dnf:
    name: "{{ tools }}"
    state: "present"
  become: yes
  become_user: "root"
  tags: 
    - secured

- name: "Set the custom aliases and functions"
  import_tasks: customAliasAndFunctions.yml
  tags: 
    - secured

- name: "Enable and start snapd."
  service:
    name: snapd
    state: started
    enabled: yes
  become: yes
  become_user: "root"
  tags:
    - secured

- name: "Ensure snapd is updated"
  snap:
    name: core
    state: present
  become: yes
  become_user: "root"
  tags:
    - secured


- name: "Ensure snap core is refreshed"
  shell: 'snap refresh core'
  become: yes
  become_user: "root"
  tags:
    - secured

- name: "Install certbot"
  snap:
    name: certbot
    classic: yes
  become: yes
  become_user: "root"

- name: "Link certbot executable from snapd to usr."
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link


- name: "Install nodejs"
  include_role: 
    name: ansible-role-nodejs
    apply:
      tags: 
        secured