---
# tasks file for customizeVPS
- name: "Install all tools used"
  dnf:
    name: "{{ tools }}"
    state: "present"
  become: yes
  become_user: "root"
  tags: 
    - secured

- name: "Set the custom aliases and functions"
  import_tasks: customAliasAndFunctions.yml
  tags: 
    - secured

- name: "Enable and start snapd."
  service:
    name: snapd
    state: started
    enabled: yes
  tags:
    - secured

- name: "Install nodejs"
  include_role: 
    name: ansible-role-nodejs
    apply:
      tags: 
        secured