---
# tasks file for customizeVPS
- name: "Install all tools used"
  dnf:
    name: "{{ item }}"
    state: "present"
  become: yes
  become_user: "root"
  with_items: "{{ tools }}"
  tags: 
    - secured

- name: "Set the custom aliases and functions"
  include_tasks: customAliasAndFunctions.yml
  apply:
    tags:
      - secured
  tags: 
    - secured


     