---
# tasks file for MediaWiki
- name: "Install prerequisits"
  include_tasks: prerequisites.yml
  apply:
    tags:
        - secured
        - mediawiki
  tags: 
    - secured
    - mediawiki

- name: "Install MariaDB"
  include_role: ansible-role-mysql
  apply:
    tags:
      - secured
      - mediawiki
  tags: 
    - secured
    - mediawiki

- name: "Install Apache 2.4.35+"
  include_role: ansible-role-apache
  apply:
    tags:
        - secured
        - mediawiki
  tags: 
    - secured
    - mediawiki
  
