---
# tasks file for MediaWiki
- name: "Install prerequisits"
  import_tasks: prerequisites.yml
  tags: [secured, mediawiki]

- name: "Install MariaDB"
  include_role: 
    name: ansible-role-mysql
    apply:
      tags:
        [secured, mediawiki]
  tags: [secured, mediawiki]

  tags: [secured, mediawiki]

- name: "Install Apache 2.4.35+"
  include_role: 
    name: ansible-role-apache
    apply:
      tags:
        [secured, mediawiki]
  tags: [secured, mediawiki]

- name: "Download and unzip the archive."
  unarchive:
    src: '{{ wikimedia_download_url }}'
    dest: '/var/www/'
    remote_src: yes
  tags: [secured, mediawiki] 

- name: "Clean up the wikimedia folder."
  command: 'mv /var/www/{{ mediawiki_package }} /var/www/wiki.{{ domain }}'
  tags: [secured, mediawiki]

- name: "Set vhost for wikimedia"
  include_role: 
    name: manage-apache-vhost
  vars:
    - vhost_vars: "{{ vhost_vars_play }}"