---
# tasks file for MediaWiki
- name: "Install prerequisits"
  import_tasks: prerequisites.yml
  tags: mediawiki

- name: "Install MariaDB"
  include_role: 
    name: ansible-role-mysql
    apply:
      tags:
        mediawiki
  tags: mediawiki

  tags: mediawiki

- name: "Install Apache 2.4.35+"
  include_role: 
    name: ansible-role-apache
    apply:
      tags:
        mediawiki
  tags: mediawiki

- name: "Download and unzip the archive."
  unarchive:
    src: '{{ wikimedia_download_url }}'
    dest: '/var/www/'
    remote_src: yes
  tags: mediawiki

- name: "Ensure wikimedia content folder exists."
  file:
    path: '/var/www/wiki.{{ domain }}'
    state: directory
  tags: mediawiki

- name: "Copy content of wikimedia archive to content folder."
  copy: 
    src: '/var/www/{{ mediawiki_package }}/'
    dest: '/var/www/wiki.{{ domain }}'
    remote_src: yes
  tags: mediawiki

- name: "Remove old folder."
  command: 'rm -r /var/www/{{ mediawiki_package }}'
  tags: mediawiki

- name: "Set vhost for wikimedia"
  include_role: 
    name: manage-apache-vhost
    apply:
      tags: 
        mediawiki
  vars:
    - vhost_vars: "{{ vhost_vars_play }}"
  tags: mediawiki

- name: Copy LocalSettings.php
  template:
    src: LocalSettings.php.j2
    dest: '/var/www/wiki.{{ domain }}/LocalSettings.php'
  tags: mediawiki