- name: Crete database
  mysql_db:
    name: "{{ firefly_DB_DATABASE }}"
    state: present
  become: yes
  tags:
    - firefly
    - mysql 


- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ firefly_DB_USERNAME }}"
    host: "{{ firefly_DB_HOST | default('localhost') }}"
    password: "{{ firefly_DB_PASSWORD }}"
    priv: "{{ firefly_DB_DATABASE }}.*:ALL,GRANT"
    state: "present"
    append_privs: "no"
    encrypted: "no"
  no_log: true
  become: true
  tags:
    - firefly
    - mysql 
    - mysql-user
