- name: Copy vhost for firefly-iii
  template:
    src: firefly.domain.com.conf.j2
    dest: "/etc/httpd/sites-available/{{ firefly_WEBSITE }}.conf"
  become: yes
  tags:
    - firefly
    - firefly-apache
  
- name: Create symlink to new apache vhost config
  command: 
    cmd: "a2ensite {{ firefly_WEBSITE }}"
  when: firefly_ACTIVATE == "true"
  notify: firefly-apache-restart
  become: yes
  tags:
    - firefly
    - firefly-apache

- name: Create symlink to new apache vhost config
  command: 
    cmd: "a2dissite {{ firefly_WEBSITE }}"
  when: firefly_ACTIVATE == "false"
  notify: firefly-apache-restart
  become: yes
  tags:
      - firefly
      - firefly-apache
  
