---
# tasks file for firefly-iii
- name: Check and instal prerequired php and php modules
  import_role: 
    name: ansible-role-php
  tags:
    - php
    - firelfy

- name: Download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  become: yes
  tags:
    - php
    - firefly

- name: Install composer
  command: >
    php composer-installer.php --install-dir=/usr/local/bin --filename=composer
    chdir=/tmp
  become: yes
  tags:
    - php
    - firefly

- name: Make directory for firefly
  file:
    path: "/var/www/{{ firefly_ROOT }}"
    state: directory
    mode: '0755'
    recurse: yes
  become: yes
  tags:
    - firefly

- name: Download and compose firefly
  command: "/usr/local/bin/composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii {{ composer_version }}"
  become: yes
  tags:
    - firefly  

- name: Copy .env
  template: 
    src: .env.j2
    dest: "/var/www/{{ firefly_directory }}/.env"
  become: yes
  tags:
    - firefly
    - firefly_config

- name: Database tasks
  include_tasks: "firefly_{{ firefly_DB_HOST }}.yml"
  tags:
    - firefly
    - firefly_DB

- name: Apache tasks
  include_tasks: firelfy_apache.yml
  tags:
    - firefly
    - firelfy_apache

