---
# handlers file for SecureVPS
- name: "Restart sshd"
  service:
    name: "sshd"
    state: "restarted"
  tags:
    - basic
  
- name: "Restart fail2ban"
  service:
    name: "fail2ban"
    state: "restarted"
  become: yes
  become_user: "root"
  tags:
    - secured
  
- name: "Restart firewalld"
  service:
    name: "firewalld"
    state: "restarted"
  become: yes
  become_user: "root"
  tags:
    - secured